#!/usr/bin/env bash

MAILDIR="$HOME/Mail"
BAT="/sys/class/power_supply/BAT1/capacity"
INAME="enp9s0"

clock () {
    echo "Date: $(date "+%H:%M %a %e %b")"
}

ram () {
    local line="$(free -m | grep 'Mem:' | sed 's/ \+/ /g')"
    local current="$(cut -d ' ' -f3 <<< "$line")"
    local total="$(cut -d ' ' -f2 <<< "$line")"
    echo "Ram: $current/$total"
}

home_files() {
    echo "Home: $(ls -Al "$HOME"| wc -l)"
}

todo() {
    local file="$HOME/.config/todo"
    [ -f "$file" ] || touch "$file"

    echo "Todo: $(wc -l "$file" | cut -d ' ' -f1)"
}

unread_mail() {
    [ -d $MAILDIR ] || return -1

    local count=0
    for inbox in $MAILDIR/*/*; do
        ((count+=$(ls -1 "$inbox/new" | wc -l)))
    done
    echo "Mail: $count"
}

net() {
    local today=$(vnstat -i $INAME | grep "today" \
        | awk '{print $8" "substr ($9, 1, 1)}')
    local month=$(vnstat -i $INAME | grep "$(date +"%Y-%m")" \
        | awk '{print $8" "substr ($9, 1, 1)}' | sed '/^\s*$/d')
    echo "Today: $today Month: $month"
}

battery() {
    [ -f $BAT ] || return -1
    echo "Bat: $(cat $BAT)"
}

while true; do
    RESULT="$(net) $(unread_mail &) $(todo) $(home_files) $(battery) $(ram &) $(clock)"
    wait
    xsetroot -name "$RESULT" #"$(net) $(unread_mail) $(todo) $(home_files) $(battery) $(ram) $(clock)"
    sleep 3
done
