#!/usr/bin/env sh

MAILDIR="$HOME/Mail"

clock () {
    date "+%H:%M %a %e %b"
}

ram () {
    local line="$(free -m | grep 'Mem:' | sed 's/ \+/ /g')"
    local current="$(cut -d ' ' -f3 <<< "$line")"
    local total="$(cut -d ' ' -f2 <<< "$line")"
    echo "$current/$total"
}

home_files() {
    echo "$(ls -Al "$HOME"| wc -l)"
}

todo() {
    local file="$HOME/.config/todo"
    [ -f "$file" ] || touch "$file"

    echo "$(wc -l "$file" | cut -d ' ' -f1)"
}

unread_mail() {
    local count=0
    local inboxes="$(find $maildir -type d -name INBOX)"
    for inbox in  $inboxes; do
        ((count+=$(ls -1 "$inbox/new" | wc -l)))
    done
    echo "$count"
}

while true; do
    LINE=""
    [ -d $MAILDIR ] && LINE+="Mail: $(unread_mail) "
    LINE+="Todo: $(todo) "
    LINE+="Home: $(home_files) "
    LINE+="Ram: $(ram) "
    LINE+="Time: $(clock)"

    xsetroot -name "${LINE}"

    sleep 2
done
